### ISSUE TITLE
Some concerns

### ISSUE THREAD

**Issue by yT7Af9Fc** [KikoTs/betterdiscord-together#3]
There is already a plugin called [DiscordActivities](https://betterdiscord.app/plugin/DiscordActivities) with over 40k downloads that does the same thing, enable activities. Why submit another plugin?
If you consider your plugin to be better why not make a PR so there aren't multiple plugins that do the exact same thing in the website?

Also, the name is confusing. It's called "together" (because of Watch YT Together I guess) but the plugin enables all activities, not just YT Together.

And some (most) of the activites that it enables aren't even available to use (either "This server doesn't have access to the requested activity" or "Unable to Launch Activity" so why add them?

**Comment by KikoTs** [comment]
As I pointed this is port of the powercord plugin, powercord-together, it provides dev builds of the games, that as much as I can see now this requires special servers in order to work and I've submitted this plugin before 2 months while all these features were working.
